beta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='beta_dashboard')),
    path('blog/', include('blog.urls', namespace='beta_blog')),
    path('custom_ad/', include('custom_ad.urls', namespace='beta_custom_ad')),
    path('ep/', include('ep.urls', namespace='beta_ep')),
    path('it/', include('it.urls', namespace='beta_it')),
    path('projects/', include('projects.urls', namespace='beta_projects')),
    path('sit/', include('sit.urls', namespace='beta_sit')),

]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name="blog_index"),
]

custom_ad/urls.py
from django.urls import path
from . import views

app_name = 'custom_ad'

urlpatterns = [
    path('', views.custom_ad_index, name="custom_ad_index"),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_index, name="dashboard_index"),
]

ep/urls.py
from django.urls import path
from . import views

app_name = 'ep'

urlpatterns = [
    path('', views.ep_index, name="ep_index"),
]

it/urls.py
from django.urls import path
from . import views

app_name = 'it'

urlpatterns = [
    path('', views.it_index, name="it_index"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects_index, name="projects_index"),
]

sit/urls.py
from django.urls import path
from . import views

app_name = 'sit'

urlpatterns = [
    path('', views.sit_index, name="sit_index"),
]

custom_ad/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

ep/models.py
from django.db import models

# Create your models here.

it/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

# Create your models here.

sit/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.
def blog_index(request):
    resp_dict = {
        'current_index': 'blog'
    }
    return render(request, 'blog/blog_index.html', resp_dict)

custom_ad/views.py
from django.shortcuts import render

# Create your views here.
def custom_ad_index(request):
    resp_dict = {
        'current_index': 'custom_ad'
    }
    return render(request, 'custom_ad/custom_ad_index.html', resp_dict)

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def dashboard_index(request):
    resp_dict = {
        'current_index': 'dashboard'
    }
    return render(request, 'dashboard/dashboard_index.html', resp_dict)

ep/views.py
from django.shortcuts import render

# Create your views here.
def ep_index(request):
    resp_dict = {
        'current_index': 'ep'
    }
    return render(request, 'ep/ep_index.html', resp_dict)

it/views.py
from django.shortcuts import render

# Create your views here.
def it_index(request):
    resp_dict = {
        'current_index': 'it'
    }
    return render(request, 'it/it_index.html', resp_dict)

projects/views.py
from django.shortcuts import render

# Create your views here.
def projects_index(request):
    resp_dict = {
        'current_index': 'projects'
    }
    return render(request, 'projects/projects_index.html', resp_dict)

sit/views.py
from django.shortcuts import render

# Create your views here.
def sit_index(request):
    resp_dict = {
        'current_index': 'sit'
    }
    return render(request, 'sit/sit_index.html', resp_dict)

blog/templates/blog/blog_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_blog)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

blog/templates/blog/blog_index.html
{% extends 'blog/blog_base.html' %}
{% block body_block %}
    <h1>Beta Blog Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}

custom_ad/templates/custom_ad/custom_ad_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'custom_ad/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_custom_ad)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

custom_ad/templates/custom_ad/custom_ad_index.html
{% extends 'custom_ad/custom_ad_base.html' %}
{% block body_block %}
    <h1>Beta Custom Ad Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}

dashboard/templates/dashboard/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_dashboard)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

dashboard/templates/dashboard/dashboard_index.html
{% extends 'dashboard/dashboard_base.html' %}
{% block body_block %}
    <h1>Beta Dashboard Homepage</h1>
    <h6>{{ current_index }}</h6>
    
    <ol>
        <li><a href="{% url 'blog:blog_index' %}">Blog</a></li>
        <li><a href="{% url 'custom_ad:custom_ad_index' %}">Custom Ad</a></li>
        <li><a href="{% url 'ep:ep_index' %}">Ep</a></li>
        <li><a href="{% url 'it:it_index' %}">It</a></li>
        <li><a href="{% url 'projects:projects_index' %}">Projects</a></li>
        <li><a href="{% url 'sit:sit_index' %}">Sit</a></li>
        <li><a href="{% url 'dashboard:dashboard_index' %}">Dashboard</a></li>
    </ol>
{% endblock %}

ep/templates/ep/ep_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'ep/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_ep)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

ep/templates/ep/ep_index.html
{% extends 'ep/ep_base.html' %}
{% block body_block %}
    <h1>Beta Ep Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}

it/templates/it/it_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'it/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_it)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

it/templates/it/it_index.html
{% extends 'it/it_base.html' %}
{% block body_block %}
    <h1>Beta it Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}

projects/templates/projects/projects_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_blog)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

projects/templates/projects/projects_index.html
{% extends 'projects/projects_base.html' %}
{% block body_block %}
    <h1>Beta projects Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}

sit/templates/sit/sit_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'sit/css/base.css' %}">
    {% block css_tags %}{% endblock %}
    {% block defer_scripts %}{% endblock %}
</head>
<body>
    <nav>
        <a href="{% url 'dashboard:dashboard_index' %}">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>
    {% block body_block %}{% endblock %}
    <footer>
        &copy; 2023 My Website. All rights reserved. (beta_sit)
    </footer>
    {% block script_tags %}{% endblock %}
</body>
</html>

sit/templates/sit/sit_index.html
{% extends 'sit/sit_base.html' %}
{% block body_block %}
    <h1>Beta sit Homepage</h1>
    <h6>{{ current_index }}</h6>
{% endblock %}